import MyAppBar from "@/components/common/MyAppBar";
import Head from "next/head";
import { useState } from "react";
import { ThemeProvider } from "@mui/material";
import { lightTheme, darktheme } from "@/styles/mui/theme";

export default function Blog() {
  const [currentTheme,setCurrentTheme]=useState("dark")
  return (
    <>
    <ThemeProvider theme={currentTheme === "dark" ? darktheme:lightTheme}>
      <Head>
        <title>Blog |The Movie Lovers Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <MyAppBar currentTheme={currentTheme} setCurrentTheme={setCurrentTheme} />
      </div>
      </ThemeProvider>
    </>
  );
}
