import Head from "next/head";
import { useState } from "react";

//MUi Components
import Box from '@mui/material/Box';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import MenuIcon from '@mui/icons-material/Menu';
import MyAppBar from '@/components/common/MyAppBar'
import { ThemeProvider } from "@mui/material";
import { theme } from "@/styles/mui/theme";
import { darktheme } from "@/styles/mui/theme";

export default function Home() {
  const[ visible,setVisible]=useState(false);
  
  const movies=[
    {
      name:"Avengers",
      img:"https://th.bing.com/th/id/OIP.wfBjdzHrqL6zyZCxAahRIAHaD_?w=272&h=180&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3"
    },
    {
       name:"Harry Potter",
      img:"https://th.bing.com/th/id/OIP.lcvz0_qzbexQSsIXfuFfbQHaEo?w=320&h=187&c=7&r=0&o=7&dpr=1.5&pid=1.7&rm=3"
 
    }
   
  ]
  return (
    <>
    <ThemeProvider theme={theme}>
      <Head>
        <title>The Movie Lovers Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Box sx={{ flexGrow: 1 }}>
      <MyAppBar/>
    </Box>
    <Button onClick={()=>setVisible(!visible)}>
      Toggle 
    </Button>
     <Box height="200px"></Box>
    {
      visible? (<Box  sx={{background:"pink",height:"200px", width:"500px"}}>    </Box>)  :(<></>)


    }

  
     
        </div>
      </ThemeProvider>
    </>
  );
}
